import { connectDb } from "../config/db.js";
import { assertEnv } from "../config/env.js";
import { Category,Competition,Counter,EventSettings,Registration } from "../models/index.js";
import { categorySeeds,competitionSeeds } from "./catalog.js";
assertEnv();await connectDb();
const categories=[];
for(let i=0;i<categorySeeds.length;i++){const[roman,minMonths,maxMonths]=categorySeeds[i];categories.push(await Category.findOneAndUpdate({key:`cat-${i+1}`},{$set:{name:`Category ${roman}`,nameTa:`வயதுப் பிரிவு ${roman}`,minMonths,maxMonths,active:true,order:i+1}},{new:true,upsert:true,runValidators:true}));}
for(const[key,name,tamil,kind,catNums,language,image,instructions]of competitionSeeds){const c=await Competition.findOneAndUpdate({key},{$set:{name,tamil,kind,categoryIds:catNums.map(n=>categories[n-1]._id),fee:0,capacity:200,status:"Open",instructions,instructionsTa:"போட்டிக்கான தேவையான பொருட்களுடன் நேரத்திற்கு முன் வரவும்.",language,image},$setOnInsert:{slotId:null,registeredCount:0}},{new:true,upsert:true,runValidators:true});const count=await Registration.countDocuments({cancelled:false,competitionIds:c._id});if(c.registeredCount!==count){c.registeredCount=count;await c.save();}}
await EventSettings.findOneAndUpdate({singleton:"main"},{$setOnInsert:{title:"Chithiram Thiruvila",titleTa:"சித்திரம் திருவிழா",presenters:"SBK VIBGYOR School & Star Guru Charitable Foundation",date:"",venue:"",registrationDeadline:"",maxEvents:2,registrationOpen:true,prefix:"26SBK",contact:"",email:"",instructionsEn:"Carry the approved participant pass to the event. Reach the venue at least 30 minutes before your first competition. Bring only the materials permitted by the organiser.",instructionsTa:"அங்கீகரிக்கப்பட்ட பங்கேற்பாளர் பாஸை நிகழ்விற்கு கொண்டு வரவும். முதல் போட்டிக்கு குறைந்தது 30 நிமிடங்களுக்கு முன் வரவும். ஏற்பாட்டாளர் அனுமதித்த பொருட்களை மட்டும் கொண்டு வரவும்.",termsEn:"The date of birth entered must be correct. Age category is calculated from the application date. A participant may select a maximum of two eligible competitions. Online registrations require online payment. Registration is valid for event entry only after organiser approval.",termsTa:"பிறந்த தேதி சரியாக இருக்க வேண்டும். விண்ணப்ப தேதியின் அடிப்படையில் வயது பிரிவு கணக்கிடப்படும். அதிகபட்சம் இரண்டு தகுதியான போட்டிகளை மட்டும் தேர்வு செய்யலாம். ஆன்லைன் பதிவுக்கு ஆன்லைன் கட்டணம் அவசியம். ஏற்பாட்டாளர் அங்கீகாரத்திற்கு பிறகே பதிவு நிகழ்வு நுழைவுக்கு செல்லுபடியாகும்.",bannerImage:"/images/festival-main.png"}},{new:true,upsert:true});
const settings=await EventSettings.findOne({singleton:"main"}).lean();const prefix=String(settings?.prefix||"26SBK").toUpperCase();const regs=await Registration.find({applicationNo:new RegExp(`^${prefix}`)}).select("applicationNo").lean();const max=regs.reduce((m,r)=>Math.max(m,Number(String(r.applicationNo).slice(prefix.length))||0),0);await Counter.findOneAndUpdate({key:`application:${prefix}`},{$max:{value:max}},{upsert:true});
console.log("Seeded 12 age categories and 17 client competitions. Competition schedules remain admin-configurable.");process.exit(0);
