import path from "node:path";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import compression from "compression";
import cookieParser from "cookie-parser";
import session from "express-session";
import MongoStore from "connect-mongo";
import pinoHttp from "pino-http";
import crypto from "node:crypto";
import { rateLimit } from "express-rate-limit";
import { env } from "./config/env.js";
import { ensureCsrf,verifyCsrf } from "./middleware/csrf.js";
import { errorHandler,notFound } from "./middleware/error.js";
import { requestContext } from "./middleware/request-context.js";
import { authRouter } from "./routes/auth.routes.js";
import { publicRouter } from "./routes/public.routes.js";
import { adminRouter } from "./routes/admin.routes.js";
import { judgeRouter } from "./routes/judge.routes.js";
import { paymentRouter } from "./routes/payment.routes.js";
export function createApp(){
  const app=express();app.set("trust proxy",1);app.disable("x-powered-by");
  app.use(pinoHttp({genReqId:req=>req.headers["x-request-id"]||crypto.randomUUID()}));app.use(requestContext);app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));app.use(compression());
  app.use(cors({origin:env.frontendOrigin,credentials:true,methods:["GET","POST","PUT","PATCH","DELETE","OPTIONS"],allowedHeaders:["Content-Type","X-XSRF-TOKEN","X-Request-ID"]}));app.use(cookieParser());
  app.use(session({name:"sbk.sid",secret:env.sessionSecret,resave:false,saveUninitialized:false,rolling:true,cookie:{httpOnly:true,secure:env.nodeEnv==="production",sameSite:"lax",maxAge:8*60*60*1000},store:MongoStore.create({mongoUrl:env.mongodbUri,collectionName:"sessions",ttl:8*60*60,autoRemove:"native"})}));app.use(ensureCsrf);
  app.use("/api/payments",express.raw({type:"application/json",limit:"1mb"}),paymentRouter);
  app.use(express.json({limit:"8mb"}));app.use(express.urlencoded({extended:false,limit:"1mb"}));app.use(verifyCsrf);
  app.use("/api",rateLimit({windowMs:60*1000,limit:300,standardHeaders:true,legacyHeaders:false}));
  app.get("/api/health",(req,res)=>res.json({ok:true,time:new Date().toISOString()}));
  app.use("/api/auth",authRouter);app.use("/api",publicRouter);app.use("/api/admin",adminRouter);app.use("/api/judge",judgeRouter);
  app.use(env.mediaPublicPath,express.static(path.resolve(process.cwd(),env.mediaDir),{fallthrough:false,maxAge:env.nodeEnv==="production"?"7d":0}));
  app.use("/api",notFound);app.use(errorHandler);return app;
}
